# 2023/05/24 現在LTSバージョンである3.11を動作環境とする
FROM python:3.11
USER root

# コピペ：https://qiita.com/jhorikawa_err/items/fb9c03c0982c29c5b6d5
RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm
RUN apt-get install -y vim less
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

## 追加
# pygame library
RUN python -m pip install pygame