version: '3'

services:
  python:
    build:
      context: ./
      dockerfile: ./dockerfile
    environment:
      - PULSE_SERVER=docker.for.mac.localhost
    # container名
    #container_name: 'python'
    container_name: 'py'
    restart: always
    # コンテナの中に入った直後の作業ディレクトリ
    #working_dir: '/root/'
    tty: true
    volumes:
      - ./mnt/:/mnt/
      - ./opt/:/opt/
      - type: bind
        source: ~/.config/pulse
        target: /root/.config/pulse