# 2023/05/24 現在LTSバージョンである3.11を動作環境とする
FROM python:3.11
#FROM python:3.9
USER root

# コピペ：https://qiita.com/jhorikawa_err/items/fb9c03c0982c29c5b6d5
RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

# pipとsetuptoolsの更新
# RUN python -m pip install --upgrade pip setuptools
# RUN pip uninstall -y setuptools
# RUN pip install -y setuptools==60.1.0
# RUN pip install -y 
# RUN pip install cocos2d \
#     pyglet==1.5.21 \
#     six==1.16 \
#     wheel==0.36.2 \
#     pip==21.3.1 \
#     cocos2d

RUN apt-get update && apt-get install -y \
   libsdl2-dev \
   libsdl2-image-dev \
   libsdl2-mixer-dev \
   libsdl2-ttf-dev \
   libasound2-dev \
   libasound2-plugins \
    libsmpeg-dev \
   libportmidi-dev \
   libswscale-dev \
   libavformat-dev \
   libavcodec-dev \
   alsa-utils \
   pulseaudio
   # \

#RUN apt-get install -y vim less
#RUN pip install --upgrade pip
#RUN pip install --upgrade setuptools

## 追加
# pygame library
RUN python -m pip install pygame
#RUN python -m pip install pygame==2.0.0.dev12

#RUN apt-get update && apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

# コンテナ内で実行するコマンドを指定する（例として、スクリプトの実行コマンドを追加）
#CMD ["python", "your_script.py"]